---
title: "Electronic Resource Report"
author: "AJM"
date: "August 30, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(mosaic)
library(xlsx)
library(tidyverse)
library(readxl)
library(zoo)
library(lubridate)
library(scales)
library(knitr)

# Setting up the folders
input.folder <- "C:/DataScience/inputs"
output.folder <- "C:/DataScience/outputs"
DB1folder <- "C:/DataScience/inputs/DB1Reports"
JR1folder <- "C:/DataScience/inputs/JR1Reports"
```

```{r Data Import, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
source("1a - ImportTidy - DB1.R")
```

## Database Usage

```{r Database Usage Set Up, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
# Defines source of database usage data and functions.
source("2a - Transform - DBUsage.R")

# Creates master of usage (by academic term)
# Planning on filtering this data in each subsection.
master.usage.table <- usage.sum.database.acad.term("Communication & Mass Media Complete", 2014, 2018)
```
This section of the report shows database usage by looking at Counter Reports.

```{r Overview Graph}
# Put the database overview graph here.
usage.graph.database("Communication & Mass Media Complete", 2014, 2018)
```

### Database Usage - Record Views
```{r}
record.views <- master.usage.table %>%
  filter(User_Activity == "Record Views") %>%
  ungroup() %>%
  select(-Database)

kable(record.views)
```

```{r}
usage.graph.database.acad.term("Communication & Mass Media Complete", 2014, 2018)
```

\newpage
## Financial Information
```{r Database Financial Set Up, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
# Defines source of database usage data and functions.
source("1c - ImportTidy - Financials.R")
source("2b2 - Transform - Financial Details.R")
```

```{r}
kable(cost.database.change("Communication & Mass Media Complete", 2014, 2018))
```


```{r}
# Cost Graph
cost.database.graph("Communication & Mass Media Complete", 2014, 2018)
```

\newpage
## Cost Per Use
```{r Cost Per Use Set Up, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
# Defines source of cost per use data and functions.
source("2c - Transform - DBCostPerUse.R")
```

```{r}
cpu.database.graph("Communication & Mass Media Complete", 2014, 2018)
```


